version: '3'

services:

  bdd:

    container_name : mysql
    image : mysql
    environment:
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD : enieni

    expose :
      - "3306"
    ports :
      - "3306:3306"
    volumes :
      - bdd-data:/var/lib/mysql

volumes :
  bdd-data :
